### ISSUE TITLE
Admins to be able to reset passwords

### ISSUE THREAD

**Issue by theone321** [theone321/SecretSanta#2]
Add the ability for admins to be able to reset passwords for users who have forgotten them.
This would be exclusive to the admin page.

I'm thinking this would take the form of a list of all registered users, and selecting one would bring up a page/pop-up allowing the admin to reset the password.
Resetting might be a password the admin makes up, or a randomly generated string the system creates.
Either way, the admin will need to let the user know their new password.

Should we allow people to change their password? That would be a separate issue, but I'm still posing the question here.

**Comment by magico13** [comment]
I was thinking about this and was also thinking a list of users with buttons to reset passwords, remove matches, and other similar per-user actions.

I vote that we reset it to something we know (we can even make it so we can change them to anything we want with a textbox). We can add the ability to change passwords to the user page (getmatch) and should require them to enter their current password.

How do you want to split work?

**Comment by magico13** [comment]
Done. Right now you can reset passwords to "password" and they can change their password on their user page. The admin page also lets you de-register a user, so try not to click that button on accident. I plan on expanding admin actions on users, but that's a start. It also shows if they are registered, if they have matched with someone, and if they are someone's match (but not who they're matched with at all). Doing a test locally with the database and then making it go live.
